BEGIN;
 CREATE TABLE PAPER_TO_READING_NEW(
     PROJECT_FK  INTEGER NOT NULL,
     SOURCE_FK   INTEGER NOT NULL,
     STATUS      TEXT    NOT NULL CHECK (STATUS IN ('reading', 'read')),
     UPDATED_AT  TIMESTAMP NOT NULL DEFAULT (datetime('now')),
     PRIMARY KEY (PROJECT_FK, SOURCE_FK),
     FOREIGN KEY (PROJECT_FK, SOURCE_FK) REFERENCES PROJECT_TO_PAPER(PROJECT_FK, SOURCE_FK) ON DELETE CASCADE
 );
 -- Quarantine the orphans the JOIN below drops (reading status without a
 -- PROJECT_TO_PAPER membership) instead of losing the rows silently.
 INSERT INTO INTEGRITY_QUARANTINE (SOURCE_TABLE, SOURCE_KEY, REASON, PAYLOAD_JSON)
     SELECT 'PAPER_TO_READING',
            r.PROJECT_FK || ':' || r.SOURCE_FK,
            'paper_to_reading_cascade_fk: no PROJECT_TO_PAPER membership',
            json_object('PROJECT_FK', r.PROJECT_FK, 'SOURCE_FK', r.SOURCE_FK,
                        'STATUS', r.STATUS, 'UPDATED_AT', r.UPDATED_AT)
     FROM PAPER_TO_READING r
     LEFT JOIN PROJECT_TO_PAPER m ON m.PROJECT_FK = r.PROJECT_FK AND m.SOURCE_FK = r.SOURCE_FK
     WHERE m.PROJECT_FK IS NULL;
 INSERT INTO PAPER_TO_READING_NEW (PROJECT_FK, SOURCE_FK, STATUS, UPDATED_AT)
     SELECT r.PROJECT_FK, r.SOURCE_FK, r.STATUS, r.UPDATED_AT
     FROM PAPER_TO_READING r
     JOIN PROJECT_TO_PAPER m ON m.PROJECT_FK = r.PROJECT_FK AND m.SOURCE_FK = r.SOURCE_FK;
 DROP TABLE PAPER_TO_READING;
 ALTER TABLE PAPER_TO_READING_NEW RENAME TO PAPER_TO_READING;
 CREATE INDEX IF NOT EXISTS idx_paper_to_reading_source_fk ON PAPER_TO_READING (SOURCE_FK);
 COMMIT;
